branch-defaults:
  master:
    environment: himeneu-env
global:
  application_name: himeneu
  default_ec2_keyname: himeneu
  default_platform: Ruby 2.2 (Passenger Standalone)
  default_region: sa-east-1
  profile: eb-cli
  sc: git

