development:
    host: 'localhost'
    port: '6379'

# local testing environment
test:
    host: 'localhost'
    port: '6379'

# production environment
production:
    host: '104.236.232.221'
    port: '6379'
